/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StenciljsButton {
        "appearance": 'primary' | 'secondary' | 'danger' | 'warning';
    }
}
declare global {
    interface HTMLStenciljsButtonElement extends Components.StenciljsButton, HTMLStencilElement {
    }
    var HTMLStenciljsButtonElement: {
        prototype: HTMLStenciljsButtonElement;
        new (): HTMLStenciljsButtonElement;
    };
    interface HTMLElementTagNameMap {
        "stenciljs-button": HTMLStenciljsButtonElement;
    }
}
declare namespace LocalJSX {
    interface StenciljsButton {
        "appearance"?: 'primary' | 'secondary' | 'danger' | 'warning';
    }
    interface IntrinsicElements {
        "stenciljs-button": StenciljsButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stenciljs-button": LocalJSX.StenciljsButton & JSXBase.HTMLAttributes<HTMLStenciljsButtonElement>;
        }
    }
}
